added ability for compressed pointer to use full 32 bits for addressing in single tier mode and use 31 bits for addressing in multi-tier mode
intel/CacheLib pull request #41
Opened 2022-12-15 19:40 UTC by guptask

2022-12-15 23:01 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 197 at r1](https://reviewable.io/reviews/intel/cachelib/41#-NJN045F7C8PckwUZPF2:-NJN045G0ruB17nAxq50:bvyzpwv) ([raw file](https://github.com/intel/cachelib/blob/ace45f43380d3353605caeeb3f842cbf57a41599/cachelib/allocator/memory/CompressedPtr.h#L197)):*
> ```objc
>     TierId tid;
>     for (tid = 0; tid < allocators_.size(); tid++) {
>       if (allocators_[tid]->isMemoryInAllocator(static_cast<const void*>(uncompressed)))
> ```

does it compile? on upstream, allocators_ is not a vector, but just a single pointer, right?
I think you could probably just hardcode isMultiTiered to false in this function for now.


<!-- Sent from Reviewable.io -->

2022-12-16 21:05 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 197 at r1](https://reviewable.io/reviews/intel/cachelib/41#-NJN045F7C8PckwUZPF2:-NJRk3WdExZSpcNuVHhQ:blmb1hv) ([raw file](https://github.com/intel/cachelib/blob/ace45f43380d3353605caeeb3f842cbf57a41599/cachelib/allocator/memory/CompressedPtr.h#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

does it compile? on upstream, allocators_ is not a vector, but just a single pointer, right?
I think you could probably just hardcode isMultiTiered to false in this function for now.
</blockquote></details>

It compiles now. I renamed SingleTierPtrCompressor to PtrCompressor. We can revert to SingleTierPtrCompressor name later with the other changes. This is the least intrusive option in my opinion for merging into meta/main. I took out the AllocatorContainer based PtrCompressor for now.


<!-- Sent from Reviewable.io -->

2022-12-16 21:36 UTC, igchor requested changes
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 197 at r1](https://reviewable.io/reviews/intel/cachelib/41#-NJN045F7C8PckwUZPF2:-NJRr2fv4BOTpQJd8PVg:b-kg09w5) ([raw file](https://github.com/intel/cachelib/blob/ace45f43380d3353605caeeb3f842cbf57a41599/cachelib/allocator/memory/CompressedPtr.h#L197)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

It compiles now. I renamed SingleTierPtrCompressor to PtrCompressor. We can revert to SingleTierPtrCompressor name later with the other changes. This is the least intrusive option in my opinion for merging into meta/main. I took out the AllocatorContainer based PtrCompressor for now.
</blockquote></details>

Ok, makes sense. I think you can still include the implementation which operates on vector of allocators. Just please makes sure it is not used anywhere (perhaps just add some simple test for it) and it has different name than `PtrCompressor`, e.g. `MultiTierPtrCompressor` or something like this. In the previous version, both classes were named the same and that the issue for me.
___
*[`cachelib/allocator/memory/CompressedPtr.h` line 41 at r2](https://reviewable.io/reviews/intel/cachelib/41#-NJRp8UD8bqZ1obodq2A:-NJRp8UD8bqZ1obodq2B:bco0fu2) ([raw file](https://github.com/intel/cachelib/blob/1f92aaf43110715f4c062e8bb6b9d54d2f97e0cd/cachelib/allocator/memory/CompressedPtr.h#L41)):*
> ```objc
> // the 32nd bit only since its value cannot exceed kMaxTiers (2). This leaves
> // the remaining (32 - (kNumSlabBits - 6) - 1 bit for tier id) =  15 bits  for
> // the  slab  index. Hence we can index 128 GiB of memory in slabs per tier and
> ```

128 GiB of memory per tier in mutlti-tier configuration  or 256 GiB in single-tier
___
*[`cachelib/allocator/memory/CompressedPtr.h` line 118 at r2](https://reviewable.io/reviews/intel/cachelib/41#-NJRq8IR-PJlOtU9Row9:-NJRq8IS7AeqZvnSii8U:bkllmdh) ([raw file](https://github.com/intel/cachelib/blob/1f92aaf43110715f4c062e8bb6b9d54d2f97e0cd/cachelib/allocator/memory/CompressedPtr.h#L118)):*
> ```objc
>   // Number of bits for the slab index. This will be the top 16 bits of the
>   // compressed ptr.
>   static constexpr unsigned int kNumSlabIdxBits =
> ```

This change is a bit misleading I think. This value will represent number of bits used for slab indexing only for mutli-tier, for single tier it will be this value + 1, right? Maybe just replace this constant with a constexpr function?
`static constexpr unsigned inte kNumSlabIdxBits(bool isMultiTiered) { return kNumTierIdxOffset - kNumAllocIdxBits + (!isMultiTiered); }`

Then you wan't need to to add `1` in other places if isMultitTiered is `false`.


<!-- Sent from Reviewable.io -->

2022-12-16 21:38 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 197 at r1](https://reviewable.io/reviews/intel/cachelib/41#-NJN045F7C8PckwUZPF2:-NJRrlgD1JoVTwGgY9xa:b7moa4j) ([raw file](https://github.com/intel/cachelib/blob/ace45f43380d3353605caeeb3f842cbf57a41599/cachelib/allocator/memory/CompressedPtr.h#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Ok, makes sense. I think you can still include the implementation which operates on vector of allocators. Just please makes sure it is not used anywhere (perhaps just add some simple test for it) and it has different name than `PtrCompressor`, e.g. `MultiTierPtrCompressor` or something like this. In the previous version, both classes were named the same and that the issue for me.
</blockquote></details>

Or if you don;t include that implementation, please add some comment or some info in the commit message that it needs to be implemented later.


<!-- Sent from Reviewable.io -->

2022-12-19 23:55 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 197 at r1](https://reviewable.io/reviews/intel/cachelib/41#-NJN045F7C8PckwUZPF2:-NJgny5E1yW5ymCUg_tg:bb7f2mf) ([raw file](https://github.com/intel/cachelib/blob/ace45f43380d3353605caeeb3f842cbf57a41599/cachelib/allocator/memory/CompressedPtr.h#L197)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Or if you don;t include that implementation, please add some comment or some info in the commit message that it needs to be implemented later.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-12-19 23:55 UTC, guptask reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @guptask and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 41 at r2](https://reviewable.io/reviews/intel/cachelib/41#-NJRp8UD8bqZ1obodq2A:-NJgnsgt9dBATtyVrxMm:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/1f92aaf43110715f4c062e8bb6b9d54d2f97e0cd/cachelib/allocator/memory/CompressedPtr.h#L41)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

128 GiB of memory per tier in mutlti-tier configuration  or 256 GiB in single-tier
</blockquote></details>

Done.
___
*[`cachelib/allocator/memory/CompressedPtr.h` line 118 at r2](https://reviewable.io/reviews/intel/cachelib/41#-NJRq8IR-PJlOtU9Row9:-NJgnveaC75gQ0-_Z6LL:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/1f92aaf43110715f4c062e8bb6b9d54d2f97e0cd/cachelib/allocator/memory/CompressedPtr.h#L118)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This change is a bit misleading I think. This value will represent number of bits used for slab indexing only for mutli-tier, for single tier it will be this value + 1, right? Maybe just replace this constant with a constexpr function?
`static constexpr unsigned inte kNumSlabIdxBits(bool isMultiTiered) { return kNumTierIdxOffset - kNumAllocIdxBits + (!isMultiTiered); }`

Then you wan't need to to add `1` in other places if isMultitTiered is `false`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-20 00:09 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41#-:-NJgrCTGD-OF_E7CiloI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @guptask)



<!-- Sent from Reviewable.io -->

2022-12-20 23:46 UTC, byrnedj requested changes
It looks good - I just have one comment on the tests. I also was able to compile and pass all tests.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41#-:-NJlvT7cBsajV8fzBVB5:b45vylp)* status: all files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp` line 410 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJluvRF5tSFDLv7PBdq:-NJluvRG1CyQGI09E2qE:bxklhct) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp#L410)):*
> ```cpp
>   }
> 
>   ASSERT_EQ(nullptr, m.unCompress(m.compress(nullptr, false), false));
> ```

I would recommend adding the following block after this line. This way we can at least say the code is tested. In fact, I tried adding this and it passed.



_Code snippet:_
```cpp
   // and also test with multi-tier
   for (const auto& pool : poolAllocs) {
     const auto& allocs = pool.second;
     for (const auto* alloc : allocs) {
       CompressedPtr ptr = m.compress(alloc, true);
       ASSERT_FALSE(ptr.isNull());
       ASSERT_EQ(alloc, m.unCompress(ptr, true));
     }
   }

   ASSERT_EQ(nullptr, m.unCompress(m.compress(nullptr, true), false));
```


<!-- Sent from Reviewable.io -->

2022-12-21 18:43 UTC, vinser52 commented on cachelib/allocator/memory/CompressedPtr.h
> +class MultiTierPtrCompressor;
why do we need this forward declaration?

2022-12-21 18:43 UTC, vinser52 commented on cachelib/allocator/memory/CompressedPtr.h
> +class MultiTierPtrCompressor {
where this class template is used?

2022-12-21 18:43 UTC, vinser52 commented on cachelib/allocator/memory/CompressedPtr.h
> +                          TierId tid) noexcept {
where we are storing `tid`? I believe we need a unit test to check `compress` function

2023-01-04 00:02 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 31 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-31:-NKu2ha10Bw3fXxrGFLk:b9l79nl) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L31)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

why do we need this forward declaration?
</blockquote></details>

you're right. The forward declaration is needed because of the following in CompressedPtr class:

  template <typename PtrType, typename AllocatorContainer>
  friend class MultiTierPtrCompressor;

But for upstream PR, I took it out. I'm adding it back. 


<!-- Sent from Reviewable.io -->

2023-01-04 00:06 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 190 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-190:-NKu561V899NDLofhLZN:b-q8g8za) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L190)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

where this class template is used?
</blockquote></details>

It won't be used in the upstream PR. This is a foundational PR meant to add the framework. The MultiTierPtrCompressor will be used later. This is what Igor and I discussed.


<!-- Sent from Reviewable.io -->

2023-01-04 00:14 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: all files reviewed, 4 unresolved discussions (waiting on @guptask)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 190 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-190:-NKu6_f6Ch4Xgcf94cBz:b-s21x8c) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L190)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

It won't be used in the upstream PR. This is a foundational PR meant to add the framework. The MultiTierPtrCompressor will be used later. This is what Igor and I discussed.
</blockquote></details>

If a class template is not used anywhere the compiler does not even compile it. It means you might even have a compilation error inside such a class template and the compiler will not detect it. Maybe better to upstream this template later when it is actually used? Or (if we want to upstream it in this PR) introduce a unit test for it so that it is compiled by the compiler.


<!-- Sent from Reviewable.io -->

2023-01-06 18:49 UTC, guptask commented
*[`cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp` line 410 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJluvRF5tSFDLv7PBdq:-NL7PehNCYnXjQRmKjRP:b-8b11j9) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp#L410)):*
<details><summary><i>Previously, byrnedj (Daniel Byrne) wrote…</i></summary><blockquote>

I would recommend adding the following block after this line. This way we can at least say the code is tested. In fact, I tried adding this and it passed.
</blockquote></details>

Added


<!-- Sent from Reviewable.io -->

2023-01-06 19:07 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NKu6HiLCcOt_OsCMKzm:b-2reqlt) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

where we are storing `tid`? I believe we need a unit test to check `compress` function
</blockquote></details>

The CompressedPtr is backward compatible. The tid part is set to default 0 in CompressedPtr constructor. Also the following use case 

    bool isMultiTiered = allocators_.size() > 1;
    auto cptr = allocators_[tid]->compress(uncompressed, isMultiTiered);
    if (isMultiTiered) { // config has multiple tiers
      cptr.setTierId(tid);
    }


<!-- Sent from Reviewable.io -->

2023-01-06 19:08 UTC, guptask commented
fix added. Thanks for posting the code stub Daniel.





<!-- Sent from Reviewable.io -->

2023-01-09 09:28 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 190 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-190:-NLKr3LG13lqJmP1rLAd:btpk24c) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L190)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

If a class template is not used anywhere the compiler does not even compile it. It means you might even have a compilation error inside such a class template and the compiler will not detect it. Maybe better to upstream this template later when it is actually used? Or (if we want to upstream it in this PR) introduce a unit test for it so that it is compiled by the compiler.
</blockquote></details>

I added a baseline test.


<!-- Sent from Reviewable.io -->

2023-01-09 15:21 UTC, igchor requested changes
@guptask can you add unit test to verify that MultiTierCompressor works for both single and multiple tiers?

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41#-:-NLM6jFtBb4Yg7Sl19Sp:b-wb6pga)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @byrnedj and @vinser52)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLM6CfpBrvYXVq6kuW5:b-c8rx3d) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

The CompressedPtr is backward compatible. The tid part is set to default 0 in CompressedPtr constructor. Also the following use case 

    bool isMultiTiered = allocators_.size() > 1;
    auto cptr = allocators_[tid]->compress(uncompressed, isMultiTiered);
    if (isMultiTiered) { // config has multiple tiers
      cptr.setTierId(tid);
    }
</blockquote></details>

But why isn't the tid used somehow inside this function? I get that we don't pass anything but 0 as tid but still, it should work for any tid (0 or 1).


<!-- Sent from Reviewable.io -->

2023-01-09 15:46 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLMCKe80QmEcaIXq2My:bp0tjts) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

But why isn't the tid used somehow inside this function? I get that we don't pass anything but 0 as tid but still, it should work for any tid (0 or 1).
</blockquote></details>

Yeah, this is exactly my point, as Igor described.


<!-- Sent from Reviewable.io -->

2023-01-09 15:47 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @byrnedj, @guptask, and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 31 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-31:-NLMCdiF1oQ5WAStIjiG:b-r6jvz5) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L31)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

you're right. The forward declaration is needed because of the following in CompressedPtr class:

  template <typename PtrType, typename AllocatorContainer>
  friend class MultiTierPtrCompressor;

But for upstream PR, I took it out. I'm adding it back. 
</blockquote></details>

I still do not understand. If it is not needed right now by this PR let's remove it.


<!-- Sent from Reviewable.io -->

2023-01-09 15:50 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @byrnedj, @guptask, and @igchor)

___
*[`cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp` line 418 at r5](https://reviewable.io/reviews/intel/cachelib/41#-NLMDJEwAp4QDQME-_el:-NLMDJEwAp4QDQME-_em:b-gan62i) ([raw file](https://github.com/intel/cachelib/blob/a6eb1e9e911a21f71201cc1fc12ee0bf0fdacca4/cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp#L418)):*
> ```cpp
>       MultiTierPtrCompressor ptr = m.compress(alloc, false);
>       ASSERT_FALSE(ptr.isNull());
>       ASSERT_EQ(alloc, m.unCompress(ptr, false));
> ```

Can we add some Unit tests for multitier?


<!-- Sent from Reviewable.io -->

2023-01-10 08:50 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 31 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-31:-NLProt-Ao_0soR3VmIh:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L31)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

I still do not understand. If it is not needed right now by this PR let's remove it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-10 09:38 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLQ0OkhDQQIFrM_a47x:b-5z27oj) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Yeah, this is exactly my point, as Igor described.
</blockquote></details>

I took out MultiTierPtrCompressor for this PR. The difference between MultiTierPtrCompressor and PtrCompressor is that the 32nd bit can be reserved for tier id. In case of PtrCompressor we don't allow this 32nd bit to be set whereas in case of MultiTierPtrCompressor this 32nd bit is reserved for tier id. That's why the allocators.size() check is made to ensure whether we're dealing with single or multi-tier. In case of single tier, even if you use MultiTierPtrCompressor, it won't allow you to reserve the 32nd bit for tier id. This was done to create a common structure that'll allow all 32 bits in MultiTierPtrCompressor to be used for addressing when config is single tiered.


<!-- Sent from Reviewable.io -->

2023-01-10 09:39 UTC, guptask commented
*[`cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp` line 418 at r5](https://reviewable.io/reviews/intel/cachelib/41#-NLMDJEwAp4QDQME-_el:-NLQ21JRAfKitIu6XSNE:bqrnmm6) ([raw file](https://github.com/intel/cachelib/blob/a6eb1e9e911a21f71201cc1fc12ee0bf0fdacca4/cachelib/allocator/memory/tests/MemoryAllocatorTest.cpp#L418)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Can we add some Unit tests for multitier?
</blockquote></details>

Taking out MultiTierPtrCompressor and I added a tier test based on Daniel's suggestion above.


<!-- Sent from Reviewable.io -->

2023-01-10 09:40 UTC, guptask commented
I took out MultiTierPtrCompressor for this PR.





<!-- Sent from Reviewable.io -->

2023-01-10 11:40 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLQTM7v5SKqkFOqlya2:b8h36rb) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, guptask (Sounak Gupta) wrote…</i></summary><blockquote>

I took out MultiTierPtrCompressor for this PR. The difference between MultiTierPtrCompressor and PtrCompressor is that the 32nd bit can be reserved for tier id. In case of PtrCompressor we don't allow this 32nd bit to be set whereas in case of MultiTierPtrCompressor this 32nd bit is reserved for tier id. That's why the allocators.size() check is made to ensure whether we're dealing with single or multi-tier. In case of single tier, even if you use MultiTierPtrCompressor, it won't allow you to reserve the 32nd bit for tier id. This was done to create a common structure that'll allow all 32 bits in MultiTierPtrCompressor to be used for addressing when config is single tiered.
</blockquote></details>

Why you added `tid` input parameter but it is not used anywhere in this function?


<!-- Sent from Reviewable.io -->

2023-01-10 11:46 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @byrnedj, @guptask, and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 32 at r6](https://reviewable.io/reviews/intel/cachelib/41#-NLQUMyo0ZHxpdV_n24e:-NLQUMyo0ZHxpdV_n24f:bmqrxa7) ([raw file](https://github.com/intel/cachelib/blob/997faaa2ae8fda358afe7b7100d4c029ddb9735c/cachelib/allocator/memory/CompressedPtr.h#L32)):*
> ```objc
> // This CompressedPtr makes decompression fast by staying away from division and
> // modulo arithmetic and doing those during the compression time. We most  often
> // decompress a CompressedPtr than compress a pointer  while creating one.  This
> ```

3 extra whitespace should be removed.


<!-- Sent from Reviewable.io -->

2023-01-10 17:25 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLRgtJeEUijs2c6rSYT:b51hc5w) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why you added `tid` input parameter but it is not used anywhere in this function?
</blockquote></details>

This was meant to introduce the API change with backward compatibility. The final definition would look like what's the complete change in develop branch:

  // Compress the given slabIdx and allocIdx into a 64-bit compressed
  // pointer.
  static PtrType compress(uint32_t slabIdx, uint32_t allocIdx, bool isMultiTiered, TierId tid) noexcept {
    XDCHECK_LE(allocIdx, kAllocIdxMask);
    if (!isMultiTiered) {
      XDCHECK_LT(slabIdx, (1u << (kNumSlabIdxBits+1)) - 1);
      return (slabIdx << kNumAllocIdxBits) + allocIdx;
    }
    XDCHECK_LT(slabIdx, (1u << kNumSlabIdxBits) - 1);
    return (static_cast<uint64_t>(tid) << kNumTierIdxOffset) + (slabIdx << kNumAllocIdxBits) + allocIdx;
  }

Do you think this API change introduction is better with rest of tid details (rather than a placeholder in this PR) ?


<!-- Sent from Reviewable.io -->

2023-01-11 14:57 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/41)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/CacheLib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NLWJtpTDySC3F1bRlCD:bu9e9gt) ([raw file](https://github.com/intel/CacheLib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
> Do you think this API change introduction is better with rest of tid details (rather than a placeholder in this PR) ?
Yes, I do think that full implementation like in develop branch is what we need in this PR. The current placeholder is not completed and I think it is error-prone because in the future we might forget to complete the implementation. And I see no barrier to putting complete implementation in this PR, am I wrong?


<!-- Sent from Reviewable.io -->

2023-01-12 10:09 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 130 at r4](https://reviewable.io/reviews/intel/cachelib/41#-NJMINSNMF5OgRnPiwyj-r4-130:-NL_PXu84AWb-UvY0HRv:b-c2j9a9) ([raw file](https://github.com/intel/cachelib/blob/ad1a81f3a052117cf6801cfebd2d2a1ff6a6da4a/cachelib/allocator/memory/CompressedPtr.h#L130)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

> Do you think this API change introduction is better with rest of tid details (rather than a placeholder in this PR) ?
Yes, I do think that full implementation like in develop branch is what we need in this PR. The current placeholder is not completed and I think it is error-prone because in the future we might forget to complete the implementation. And I see no barrier to putting complete implementation in this PR, am I wrong?
</blockquote></details>

In https://github.com/intel/CacheLib/blob/develop/cachelib/allocator/memory/CompressedPtr.h
(develop branch Compressed Ptr) the PtrCompressor class requires an allocator container to be passed. In case of main branch, the PtrCompressor gets a single allocator. So raising a PR with complete set of changes from CompressedPtr would not work without rest of the multi-tier changes. The idea was to split the work into smaller chunks - that's why I broke up compressed pointer changes into 2 parts. One that can go independently; other with the multi-tier changes.

There are two options the way I see it -

Option 1. compressed pointer goes entirely with the multi-tier changes. That way the unit tests, that are in place in develop, can verify the compressed ptr part. The tid changes would be done everywhere; so compressed pointer code won't need any further change.

Option 2. The way we're doing it now. Create an initial PR that partially introduces API related changes in Compressed Pointer while keeping backward compatibility in main branch. Then the multi-tier PR can include the develop branch compressed ptr commit. Since the expectation is that API changes would already be part of main branch by that point, only the additional changes in Compressed Ptr would need review.


<!-- Sent from Reviewable.io -->

2023-01-12 16:49 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/41)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @byrnedj, @guptask, and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 133 at r8](https://reviewable.io/reviews/intel/CacheLib/41#-NLasP-GC-ExLEoroKwc:-NLasP-GC-ExLEoroKwd:b-tjzc4a) ([raw file](https://github.com/intel/CacheLib/blob/f1b532efc451c09f8bb047c9a53481996f20d86d/cachelib/allocator/memory/CompressedPtr.h#L133)):*
> ```objc
>       return (slabIdx << kNumAllocIdxBits) + allocIdx;
>     }
>     return (static_cast<uint64_t>(tid) << kNumTierIdxOffset) +
> ```

now the logic looks good, but another question should it really be `static_cast<uint64_t>`? Should it be a 32-bit value?


<!-- Sent from Reviewable.io -->

2023-01-12 17:03 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/41)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @byrnedj, @guptask, and @igchor)

___
*[`cachelib/allocator/memory/CompressedPtr.h` line 157 at r8](https://reviewable.io/reviews/intel/CacheLib/41#-NLavhKo--6hVc8hr7pz:-NLavhKo--6hVc8hr7q-:b-fskgoh) ([raw file](https://github.com/intel/CacheLib/blob/f1b532efc451c09f8bb047c9a53481996f20d86d/cachelib/allocator/memory/CompressedPtr.h#L157)):*
> ```objc
> 
>   void setTierId(TierId tid) noexcept {
>     ptr_ += static_cast<uint64_t>(tid) << kNumTierIdxOffset;
> ```

As we discussed, it also should be `static_cast<32>`


<!-- Sent from Reviewable.io -->

2023-01-12 17:11 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 133 at r8](https://reviewable.io/reviews/intel/cachelib/41#-NLasP-GC-ExLEoroKwc:-NLaxoA65JeoBP7hKv4Z:bt4un9) ([raw file](https://github.com/intel/cachelib/blob/f1b532efc451c09f8bb047c9a53481996f20d86d/cachelib/allocator/memory/CompressedPtr.h#L133)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

now the logic looks good, but another question should it really be `static_cast<uint64_t>`? Should it be a 32-bit value?
</blockquote></details>

changed to 32 bits. 


<!-- Sent from Reviewable.io -->

2023-01-12 17:12 UTC, guptask commented
*[`cachelib/allocator/memory/CompressedPtr.h` line 157 at r8](https://reviewable.io/reviews/intel/cachelib/41#-NLavhKo--6hVc8hr7pz:-NLaxuAh2Po5fRxcPYCf:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/f1b532efc451c09f8bb047c9a53481996f20d86d/cachelib/allocator/memory/CompressedPtr.h#L157)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

As we discussed, it also should be `static_cast<32>`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-12 17:27 UTC, vinser52 approved these changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @byrnedj and @igchor)



<!-- Sent from Reviewable.io -->

2023-01-12 17:28 UTC, vinser52 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/41#-:-NLb0boA8rgLWjT_bbC3:bnfp4nl)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @byrnedj and @igchor)



<!-- Sent from Reviewable.io -->

2023-01-12 19:00 UTC, igchor approved these changes

2023-01-17 18:44 UTC, closed without merging