Code coverage support for CacheLib
intel/CacheLib pull request #50
Opened 2023-01-06 18:39 UTC by guptask

Packages needed are lcov and genhtml.
Coverage requires addition of new compile and linker flags. It can be encapsulated as an option. Currently it is the hard-coded.

2023-01-09 16:29 UTC, igchor requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/50)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`cachelib/CMakeLists.txt` line 89 at r1](https://reviewable.io/reviews/intel/cachelib/50#-NLML3s9DPKrN3cxv1fg:-NLML3s9DPKrN3cxv1fh:b-d7krfm) ([raw file](https://github.com/intel/cachelib/blob/5f09027f12071e57f8f5f8967881bcd972f35887/cachelib/CMakeLists.txt#L89)):*
> ```CMake
> 
> # Add code coverage
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage -fprofile-arcs -ftest-coverage")
> ```

Can add an option to enable/disable coverage?

Something like:
```
if(COVERAGE_ENABLED)
    # Add code coverage
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage -fprofile-arcs -ftest-coverage")
endif()
```


<!-- Sent from Reviewable.io -->

2023-01-17 23:13 UTC, guptask commented
*[`cachelib/CMakeLists.txt` line 89 at r1](https://reviewable.io/reviews/intel/cachelib/50#-NLML3s9DPKrN3cxv1fg:-NM1-UtBCG9EgQf4Jtp7:b-896fix) ([raw file](https://github.com/intel/cachelib/blob/5f09027f12071e57f8f5f8967881bcd972f35887/cachelib/CMakeLists.txt#L89)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Can add an option to enable/disable coverage?

Something like:
```
if(COVERAGE_ENABLED)
    # Add code coverage
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --coverage -fprofile-arcs -ftest-coverage")
endif()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-18 00:54 UTC, igchor reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/50)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @guptask)

___
*[`run_code_coverage.sh` line 11 at r2](https://reviewable.io/reviews/intel/cachelib/50#-NM1McwQ3sfhBJmedMoK:-NM1McwQ3sfhBJmedMoL:b-sxvj05) ([raw file](https://github.com/intel/cachelib/blob/c6598b7b89365ba84e92793f360bd28e4ae1d073/run_code_coverage.sh#L11)):*
> ```Shell
> 
> # Track coverage
> lcov -c -i -b . -d . -o Coverage.baseline
> ```

what is this Coverage.baseline? what does it contain if no tests were run?


<!-- Sent from Reviewable.io -->

2023-01-18 00:56 UTC, igchor approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/intel/cachelib/50#-:-NM1Mu_C3PkL9jz1TlU9:bnfp4nl)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @guptask)

___
*[`run_code_coverage.sh` line 3 at r2](https://reviewable.io/reviews/intel/cachelib/50#-NM1N-mfCSL4g9P76gwZ:-NM1N-mfCSL4g9P76gw_:by2odsr) ([raw file](https://github.com/intel/cachelib/blob/c6598b7b89365ba84e92793f360bd28e4ae1d073/run_code_coverage.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> BUILD_DIR='build-cachelib'
> ```

I'm not sure if you should put compilation/installation step here - it would be better for this script to be standalone.


<!-- Sent from Reviewable.io -->

2023-01-18 17:53 UTC, guptask commented
*[`run_code_coverage.sh` line 3 at r2](https://reviewable.io/reviews/intel/cachelib/50#-NM1N-mfCSL4g9P76gwZ:-NM5-jjg1UuyIUkto9qS:b5r1idn) ([raw file](https://github.com/intel/cachelib/blob/c6598b7b89365ba84e92793f360bd28e4ae1d073/run_code_coverage.sh#L3)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if you should put compilation/installation step here - it would be better for this script to be standalone.
</blockquote></details>

Are you saying it is better to split this into 2 scripts - build_coverage and generate_coverage ?


<!-- Sent from Reviewable.io -->

2023-01-18 17:55 UTC, guptask commented
*[`run_code_coverage.sh` line 11 at r2](https://reviewable.io/reviews/intel/cachelib/50#-NM1McwQ3sfhBJmedMoK:-NM5-w8wAptS7N4fODt8:bo02tmy) ([raw file](https://github.com/intel/cachelib/blob/c6598b7b89365ba84e92793f360bd28e4ae1d073/run_code_coverage.sh#L11)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what is this Coverage.baseline? what does it contain if no tests were run?
</blockquote></details>

Even if you don't run unit tests, the coverage report shows non-zero coverage for few files. I'm not sure exactly why that is the case. These commands allow us to include those coverage stats in the final report.


<!-- Sent from Reviewable.io -->

2023-01-20 18:14 UTC, merged