Improvements to the background workers
intel/CacheLib pull request #96
Opened 2023-09-08 18:47 UTC by byrnedj

The main improvements are:
1. bulk add/remove from mmContainer
2. bulk eviction
3. better scheduling of background threads and calculating batch sizes
4. improved stats (including those from https://github.com/guptask/CacheLib/tree/dsa_bgknd_bulk_evictions)
5. ability for background workers to evict/promote without mark moving bit - we can use acquire instead

The results are - nearly 20% improvement in multi-tier (develop branch) performance with this config:
[simple_tiers_test_bg.txt](https://github.com/pmem/CacheLib/files/12562850/simple_tiers_test_bg.txt)

2023-09-14 19:28 UTC, igchor reviewed
> Reviewed 14 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 14 of 29 files reviewed, 8 unresolved discussions (waiting on @byrnedj)

___
*[`cachelib/allocator/BackgroundMover-inl.h` line 82 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK23nWDItNVG3zvlL4:-NeK23nWDItNVG3zvlL5:b8r5t6p) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L82)):*
> ```objc
>   auto assignedMemory = mutex.lock_combine([this] { return assignedMemory_; });
> 
>   while (true) {
> ```

Why? Isn't it better to let PeriodicWorker schedule the work?
___
*[`cachelib/allocator/BackgroundMoverStrategy.h` line 61 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK2EhCEQl2HE9n0Nnz:-NeK2EhCEQl2HE9n0No-:bxpyr2f) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMoverStrategy.h#L61)):*
> ```objc
> };
> 
> /*
> ```

Can you remove it if it's not needed anymore?
___
*[`cachelib/allocator/Cache.h` line 84 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK38UP3ypIR3r6HVcz:-NeK38UP3ypIR3r6HVd-:bg6iov6) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/Cache.h#L84)):*
> ```objc
> 
>     bool operator<(const MemoryDescriptorType& rhs) {
>         if (this->tid_ < rhs.tid_) return true;
> ```

nit: you can implement this like this:
`return std::make_tuple(tid_, pid_, cid_) < std::make_tuple(rhs.tid_, rhs.pid_, rhs.cid)`

Same is true for operator==.
___
*[`cachelib/allocator/Cache.h` line 108 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK2XLo9j6Rq3lU8yTv:-NeK2XLo9j6Rq3lU8yTw:b-7r0u1w) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/Cache.h#L108)):*
> ```objc
> };
> 
> inline bool operator<(const MemoryDescriptorType& lhs, const MemoryDescriptorType& rhs) {
> ```

nit: I don't think you need to implement this operator as a free function if you already have a member operator<
___
*[`cachelib/allocator/Cache.h` line 119 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK2dTs69Rag7NMviqd:-NeK2dTs69Rag7NMviqe:b-vdhdo0) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/Cache.h#L119)):*
> ```objc
>   return false;
> }
> inline bool operator==(const MemoryDescriptorType& lhs, MemoryDescriptorType& rhs) {
> ```

nit: same here
___
*[`cachelib/allocator/CacheAllocator.h` line 2075 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK4eEeC16FujAIG3Kg:-NeK4eEeC16FujAIG3Kh:b77eptn) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/CacheAllocator.h#L2075)):*
> ```objc
>     uint32_t currItems = mmContainer.size();
>     if (currItems < batch) {
>         batch = currItems/2;
> ```

why / 2?
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 444 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK7as19d6WmoUR4zWU:-NeK7as19d6WmoUR4zWV:bkll9fs) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/CacheAllocator-inl.h#L444)):*
> ```objc
>       return memory;
>     } else {
>       if (memory.size() != 0) {
> ```

I would suggest using some wrapper for freeing the memory - if you do this manually, you need to be very careful about potential exceptions.
___
*[`cachelib/allocator/CacheAllocator-inl.h` line 1806 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK8bov40c5m7B54Udd:-NeK8bowAflrIdYSG64K:b-jmgipc) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/CacheAllocator-inl.h#L1806)):*
> ```objc
>                                              bool markMoving,
>                                              bool fromBgThread) {
>   std::vector<Item*> newAllocs;
> ```

I'm not sure if this makes a big difference but with so many vectors we will have quite a lot of dynamic memory allocations which can impact performance. You might want to consider putting all of those variables into a tuple/struct and having just a single vector (which you should reserve()).
___
*[`cachelib/allocator/memory/MemoryPool.cpp` line 292 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK7A5v5HoNirkDI9Km:-NeK7A5v5HoNirkDI9Kn:b-3a15tg) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/memory/MemoryPool.cpp#L292)):*
> ```cpp
>   // allocation class ids that need slab to initiate an allocation.
>   LockHolder l(lock_);
>   auto allocs2 = ac.allocateBatch(remain);
> ```

I don't quite get the logic here. If we failed to make `batch` allocations before why do you expect it to succeed now?


<!-- Sent from Reviewable.io -->

2023-09-18 10:29 UTC, vinser52 reviewed
> Reviewed 1 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 14 of 29 files reviewed, 11 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeOPPv68kPYnEwrv9dH:-NeOPPv68kPYnEwrv9dI:b-2gf960) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/CMakeLists.txt#L46)):*
> ```CMake
> 
> option(BUILD_TESTS "If enabled, compile the tests." ON)
> option(WITH_DTO "If enabled, build with DSA transparent offloading." OFF)
> ```

nit: I would add `BUILD_` prefix to `WITH_DTO`: `BUILD_WITH_DTO`.
___
*[`cachelib/allocator/BackgroundMover.h` line 68 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeOPpFjB6oLHNSBtYjN:-NeOPpFjB6oLHNSBtYjO:b-6r61x1) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover.h#L68)):*
> ```objc
> 
>   BackgroundMoverStats getStats() const noexcept;
>   std::map<MemoryDescriptorType,uint64_t> getClassStats() const noexcept;
> ```

nit: I would add an alias for the `std::map<MemoryDescriptorType,uint64_t>`, e.g. `using class_moves_map_type = std::map<MemoryDescriptorType,uint64_t>`.
And use this alias everywhere, to avoid bulk renaming (like right now you need to update multiple places) in the future.
___
*[`cachelib/allocator/MMTinyLFU.h` line 330 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NebonQB-hX-r8yamAtn:-NebonQB-hX-r8yamAto:bm3ufkw) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/MMTinyLFU.h#L330)):*
> ```objc
>     //          is unchanged.
>     bool add(T& node) noexcept;
>     bool addBatch(std::vector<T*>& nodes) noexcept;
> ```

nit: better practice to pass begin and end iterators to make interface container-independent. For example:
```
template< class InputIt>
bool addBatch(InputIt first, InputIt last) noexcept;
```


<!-- Sent from Reviewable.io -->

2023-09-18 10:38 UTC, vinser52 reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 14 of 29 files reviewed, 12 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/MMTinyLFU-inl.h` line 218 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NebrWC-9Q7xHPH1JBnT:-NebrWC-9Q7xHPH1JBnU:b-xuq5x4) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/MMTinyLFU-inl.h#L218)):*
> ```objc
> template <typename T, MMTinyLFU::Hook<T> T::*HookPtr>
> bool MMTinyLFU::Container<T, HookPtr>::addBatch(std::vector<T*>& nodes) noexcept {
>     return false;
> ```

why it is not implemented?


<!-- Sent from Reviewable.io -->

2023-09-18 16:22 UTC, vinser52 requested changes
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 14 of 29 files reviewed, 14 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/BackgroundMover-inl.h` line 39 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-Ned4A3NB422h8tdA6Qr:-Ned4A3NB422h8tdA6Qs:b-hbnwb6) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L39)):*
> ```objc
>                             std::memory_order_relaxed);
>   maxTraversalTimeNs_.store(std::max(maxTraversalTimeNs_.load(), nsTaken),
>                             std::memory_order_relaxed);
> ```

The implementation looks like not thread-safe and as I can understand `recordTraversalTime` is called by a single thread. If so, why we need to use std::atomic<> to store the statistic?
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 102 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-Ned3Uzp6WVbuNAHiBIz:-Ned3Uzp6WVbuNAHiBJ-:b-4jfat3) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L102)):*
> ```objc
>     auto end = util::getCurrentTimeNs();
>     if (moves > 0) {
>       traversalStats_.recordTraversalTime(end > begin ? end - begin : 0);
> ```

why do we need to check end > begin? is it for overflow check? if so, we need better handling for overflow: at least it is better to skip rather than write `0`.
If it is not about overflow, could you please describe when it is possible?


<!-- Sent from Reviewable.io -->

2023-11-09 01:15 UTC, byrnedj reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 9 of 29 files reviewed, 6 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeOPPv68kPYnEwrv9dH:-NildNfU0qJJVSsx3N9i:bb7f2mf) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/CMakeLists.txt#L46)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

nit: I would add `BUILD_` prefix to `WITH_DTO`: `BUILD_WITH_DTO`.
</blockquote></details>

done
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 39 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-Ned4A3NB422h8tdA6Qr:-Nil_cw87IjGckJim1TG:bjp22t6) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L39)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

The implementation looks like not thread-safe and as I can understand `recordTraversalTime` is called by a single thread. If so, why we need to use std::atomic<> to store the statistic?
</blockquote></details>

You're right - these don't need to be atomics - I have updated them and some other counters since no other thread will access them.
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 82 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK23nWDItNVG3zvlL4:-NilUMpg5zxIm2qnxp81:b5yiu86) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L82)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Why? Isn't it better to let PeriodicWorker schedule the work?
</blockquote></details>

I find that I get 20% more background evictions with this loop with translates to some improvement in throughput. The worker will run as long as there is work to do - it avoids jumping out and being rescheduled in the case that there are still items to evict.
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 102 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-Ned3Uzp6WVbuNAHiBIz:-NilZaOE5FGCdyoc2UjK:bwa90u6) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/BackgroundMover-inl.h#L102)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

why do we need to check end > begin? is it for overflow check? if so, we need better handling for overflow: at least it is better to skip rather than write `0`.
If it is not about overflow, could you please describe when it is possible?
</blockquote></details>

It is just for safety - so that the subtraction of end-begin will be greater than 0 and recordTraversalTime will always take a non-negative value. I did just copy this logic from Reaper thread.
___
*[`cachelib/allocator/MMTinyLFU-inl.h` line 218 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NebrWC-9Q7xHPH1JBnT:-NilcRWqAvu7RXZ6A6sP:b-896fix) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/MMTinyLFU-inl.h#L218)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

why it is not implemented?
</blockquote></details>

Done.
___
*[`cachelib/allocator/memory/MemoryPool.cpp` line 292 at r1](https://reviewable.io/reviews/intel/CacheLib/96#-NeK7A5v5HoNirkDI9Km:-NilcSq54h8MI4FNcs6T:b-adrqah) ([raw file](https://github.com/intel/CacheLib/blob/9642348781563ac533b46e3528ebf78fc212a3c0/cachelib/allocator/memory/MemoryPool.cpp#L292)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I don't quite get the logic here. If we failed to make `batch` allocations before why do you expect it to succeed now?
</blockquote></details>

because we hold the lock - this is the logic from the original allocate call


<!-- Sent from Reviewable.io -->

2023-11-20 19:20 UTC, igchor commented
@byrnedj  could you please split the changes logically into commits (and remove commits with fixes after review, etc.)? I would prefer not to squash all of them on merge, so that it's easier to upstream it.

Also, would it be possible to share the implementation of findEvictionBatch with findEviction? Or should we consider that after merging this and rebasing (since there are some change in upstream I think).

2023-12-01 15:32 UTC, vinser52 requested changes
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 7 of 30 files reviewed, 7 unresolved discussions (waiting on @byrnedj and @igchor)

___
*[`cachelib/allocator/BackgroundMover.h` line 56 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_z0Wx803V9gH_waL7:-Nk_z0WyDxy-1TRpe9no:b-j01nwd) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover.h#L56)):*
> ```objc
> class BackgroundMover : public PeriodicWorker {
>  public:
>   using ClassBgStatsType = std::map<MemoryDescriptorType,uint64_t>;
> ```

do you really need an ordered map?
___
*[`cachelib/allocator/BackgroundMover.h` line 81 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_wx0KEbteNiBxFsSk:-Nk_wx0KEbteNiBxFsSl:b-r62c9u) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover.h#L81)):*
> ```objc
>     void recordTraversalTime(uint64_t nsTaken);
> 
>     uint64_t getAvgTraversalTimeNs(uint64_t numTraversals) const;
> ```

Why do we need to pass `numTraversals` as a parameter? Why we cannot use the `numTraversals_` member?
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 38 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_xp-b5p7Uv_-jsw6s:-Nk_xp-b5p7Uv_-jsw6t:busfhgj) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L38)):*
> ```objc
>   minTraversalTimeNs_ = std::min(minTraversalTimeNs_, nsTaken);
>   maxTraversalTimeNs_ = std::max(maxTraversalTimeNs_, nsTaken);
>   totalTraversalTimeNs_ += nsTaken;
> ```

Should we also increment `numTraversals_`?
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 44 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_xEZ91aa6kuUdHlTG:-Nk_xEZ91aa6kuUdHlTH:b-mf1fhu) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L44)):*
> ```objc
> uint64_t BackgroundMover<CacheT>::TraversalStats::getAvgTraversalTimeNs(
>     uint64_t numTraversals) const {
>   return numTraversals ? totalTraversalTimeNs_ / numTraversals : 0;
> ```

if `numTraversals` equals `0` can we use the `numTraversals_` member and return `totalTraversalTimeNs_ / numTraversals_`?
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 131 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_zLdo3FwjI24v3oQm:-Nk_zLdp4xq9P3SJMRgc:bwuppvm) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L131)):*
> ```objc
> 
> template <typename CacheT>
> std::map<MemoryDescriptorType,uint64_t>
> ```

Use the `ClassBgStatsType` alias instead of `std::map<MemoryDescriptorType,uint64_t>`
___
*[`cachelib/allocator/BackgroundMoverStrategy.h` line 51 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_yVbvC7vTYIKQvzyq:-Nk_yVbvC7vTYIKQvzyr:b-rul09a) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMoverStrategy.h#L51)):*
> ```objc
>           batches.push_back(batch);
>         } else {
>           batches.push_back(0);
> ```

what does batch size equal `0` mean? Why we should add `0` to the returned vector?


<!-- Sent from Reviewable.io -->

2024-02-28 16:50 UTC, byrnedj reviewed
> *[Reviewable](https://reviewable.io/reviews/intel/CacheLib/96)* status: 9 of 30 files reviewed, 7 unresolved discussions (waiting on @igchor and @vinser52)

___
*[`cachelib/allocator/BackgroundMover.h` line 56 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_z0Wx803V9gH_waL7:-Nrk_DzO-s5cuxp5zuj9:b-qlmbwt) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover.h#L56)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

do you really need an ordered map?
</blockquote></details>

yes because it is nice to iterate through the (cid,pid,tid) in order during stats output. also I am avoiding implementing a hash function that is required in unordered_map
___
*[`cachelib/allocator/BackgroundMover.h` line 81 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_wx0KEbteNiBxFsSk:-Nrk_DLR0r9Uirz4LDJJ:b-896fix) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover.h#L81)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Why do we need to pass `numTraversals` as a parameter? Why we cannot use the `numTraversals_` member?
</blockquote></details>

Done.
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 38 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_xp-b5p7Uv_-jsw6s:-Nrk_41uCnuUyOiRRnZq:b-yq1wgb) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L38)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Should we also increment `numTraversals_`?
</blockquote></details>

fixed use of numTraversals - we will use the count from BackgroundMover and remove the numTraversals_ (duplicate)
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 44 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_xEZ91aa6kuUdHlTG:-Nrk_Bh98KWZB1kqWCra:b-896fix) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L44)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

if `numTraversals` equals `0` can we use the `numTraversals_` member and return `totalTraversalTimeNs_ / numTraversals_`?
</blockquote></details>

Done.
___
*[`cachelib/allocator/BackgroundMover-inl.h` line 131 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_zLdo3FwjI24v3oQm:-Nrk_2HS0Mo-_eS2ZMAg:b-896fix) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMover-inl.h#L131)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

Use the `ClassBgStatsType` alias instead of `std::map<MemoryDescriptorType,uint64_t>`
</blockquote></details>

Done.
___
*[`cachelib/allocator/BackgroundMoverStrategy.h` line 51 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nk_yVbvC7vTYIKQvzyq:-NrkZu_e63sxd4DsmOJw:b-iwbeca) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/BackgroundMoverStrategy.h#L51)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

what does batch size equal `0` mean? Why we should add `0` to the returned vector?
</blockquote></details>

added comment - it means we are already have the % free space target in this class
___
*[`cachelib/allocator/MMLru-inl.h` line 227 at r3](https://reviewable.io/reviews/intel/CacheLib/96#-Nka0vU7BiyhcQ4Q_5FE:-Nrkav0N4roXTlIE7Zj1:b-pzffo7) ([raw file](https://github.com/intel/CacheLib/blob/36129e4ace6b95a9f9c20740bc1195e5bb1a2319/cachelib/allocator/MMLru-inl.h#L227)):*
<details><summary><i>Previously, vinser52 (Sergei Vinogradov) wrote…</i></summary><blockquote>

How the node may be already in the MM container?
</blockquote></details>

it shouldn't be, I changed this to a runtime_error.:


<!-- Sent from Reviewable.io -->

2024-02-28 21:28 UTC, byrnedj commented
> @byrnedj could you please split the changes logically into commits (and remove commits with fixes after review, etc.)? I would prefer not to squash all of them on merge, so that it's easier to upstream it.
> 
> Also, would it be possible to share the implementation of findEvictionBatch with findEviction? Or should we consider that after merging this and rebasing (since there are some change in upstream I think).

I have done so. Once the rebase is finished I will rebase this branch and we can merge it.

2024-03-04 18:05 UTC, igchor commented
> > @byrnedj could you please split the changes logically into commits (and remove commits with fixes after review, etc.)? I would prefer not to squash all of them on merge, so that it's easier to upstream it.
> > Also, would it be possible to share the implementation of findEvictionBatch with findEviction? Or should we consider that after merging this and rebasing (since there are some change in upstream I think).
> 
> I have done so. Once the rebase is finished I will rebase this branch and we can merge it.

Sounds good. Regarding sharing the implementation - we can probably do it later, there might be some refactoring needed anyway or some comments from meta.

2024-03-26 20:31 UTC, merged